### ISSUE TITLE
Cannot GET /_/

### ISSUE THREAD

**Issue by SteveALee** [LearnHyperapp/hyperapp-cypress-demo#2]
I just tried to run and it fails, without updating any of the deps.
I did add `cross-env` to start as on windows and used `http-get` in test

```
"scripts": {
    "start": "cross-env NODE_ENV=development webpack-dev-server --config ./webpack.config.js",
,,,
    "test": "start-server-and-test start http-get://localhost:8080 cy:open"
  }```

The `list-spec` and `data-spec` tests fail with `Cannot GET /_/` in the cypress windowsand this in command out put

```
The automation client disconnected. Cannot continue running tests.
GET /__/ 200 6.001 ms - -
``` 

Full output is
```
$ npm test

> hyperapp-cypress@0.0.1 test C:\projects\hyperapp-cypress-demo
> start-server-and-test start http-get://localhost:8080 cy:open

starting server using command "npm run start"
and when url "http-get://localhost:8080" is responding
running tests using command "cy:open"

> hyperapp-cypress@0.0.1 start C:\projects\hyperapp-cypress-demo
> cross-env NODE_ENV=development webpack-dev-server --config ./webpack.config.js

Project is running at http://0.0.0.0:8080/
webpack output is served from /
Content not from webpack is served from C:\projects\hyperapp-cypress-demo\public
webpack: wait until bundle finished: /
Hash: 17726683421d68abc7ac
Version: webpack 3.12.0
Time: 1709ms
    Asset    Size  Chunks                    Chunk Names
bundle.js  952 kB       0  [emitted]  [big]  main
   [2] ./node_modules/hyperapp/src/index.js 10.2 kB {0} [built]
   [3] multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/index.js 40 bytes {0} [built]
   [4] (webpack)-dev-server/client?http://0.0.0.0:8080 7.93 kB {0} [built]
   [5] ./node_modules/url/url.js 23.3 kB {0} [built]
  [12] ./node_modules/strip-ansi/index.js 161 bytes {0} [built]
  [14] ./node_modules/loglevel/lib/loglevel.js 7.86 kB {0} [built]
  [15] (webpack)-dev-server/client/socket.js 1.08 kB {0} [built]
  [17] (webpack)-dev-server/client/overlay.js 3.67 kB {0} [built]
  [19] ./node_modules/html-entities/index.js 231 bytes {0} [built]
  [22] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]
  [24] (webpack)/hot/emitter.js 77 bytes {0} [built]
  [26] ./src/index.js 1.27 kB {0} [built]
  [27] ./src/actions.js 526 bytes {0} [built]
  [28] ./src/todo-item.js 218 bytes {0} [built]
  [29] ./src/index.scss 1.2 kB {0} [built]
    + 19 hidden modules
webpack: Compiled successfully.

> hyperapp-cypress@0.0.1 cy:open C:\projects\hyperapp-cypress-demo
> cypress open

GET /__/ 200 32.240 ms - -
GET /__cypress/runner/cypress_runner.css 200 73.644 ms - -
GET /__cypress/runner/cypress_runner.js 200 392.568 ms - -
GET /__cypress/static/favicon.ico 200 5.301 ms - -
GET /__cypress/iframes/integration/list_spec.js 200 8.646 ms - 721
GET /__cypress/runner/fonts/fontawesome-webfont.woff2?v=4.7.0 200 3.140 ms - 77160
GET /__cypress/tests?p=cypress\support\index.js-122 - - ms - -
GET /__cypress/tests?p=cypress\integration\list_spec.js-392 - - ms - -
GET /__cypress/iframes/integration/list_spec.js 200 6.715 ms - 721
GET /__cypress/tests?p=cypress\integration\list_spec.js-732 200 20.522 ms - -
GET /__cypress/tests?p=cypress\support\index.js-344 200 28.625 ms - -
GET /__cypress/iframes/integration/list_spec.js 200 7.164 ms - 721
GET /__cypress/tests?p=cypress\support\index.js-405 200 6.244 ms - -
GET /__cypress/tests?p=cypress\integration\list_spec.js-429 200 6.322 ms - -
HEAD / 500 4528.060 ms - -
HEAD / 500 4548.357 ms - -
HEAD / 500 4547.387 ms - -

```

**Comment by SteveALee** [comment]
CC @bahmutov - do you have any clues? I came to this from your post on cypress with hyperapp - I'm going to try with 'hyperapp V2

**Comment by SteveALee** [comment]
I updated all deps and it now works just fine.

@bahmutov I didn't use `http-get` depsite the docs for `start-server-and-test` saying is needed for `webpack-dev-server.`

**Comment by mrozbarry** [comment]
@SteveALee sorry I was late to see this. If you needed to do some changes, feel free to open a PR, I'll review it, and get it merged :)

**Comment by SteveALee** [comment]
NP, Thanks
Also FYI - some weirdness that's probably nothing to do with your code - https://github.com/cypress-io/cypress/issues/4996
